# If JANSSON_ROOT_DIR was defined in the environment, use it.
IF(NOT JANSSON_ROOT_DIR AND NOT $ENV{JANSSON_ROOT_DIR} STREQUAL "")
  SET(JANSSON_ROOT_DIR $ENV{JANSSON_ROOT_DIR})
ENDIF()

SET(_JANSSON_SEARCH_DIRS
  ${JANSSON_ROOT_DIR}
  /usr/local
  /sw # Fink
  /opt/local # DarwinPorts
  /opt/csw # Blastwave
)

FIND_PATH(JANSSON_INCLUDE_DIR jansson.h
  HINTS
    ${_JANSSON_SEARCH_DIRS}
  PATH_SUFFIXES
    include
)


FIND_LIBRARY(JANSSON_LIBRARY
  NAMES "libjansson.a"
  HINTS ${_JANSSON_SEARCH_DIRS}
  PATH_SUFFIXES lib64 lib
  )

# handle the QUIETLY and REQUIRED arguments and set JANSSON_FOUND to TRUE if 
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(JANSSON DEFAULT_MSG
    JANSSON_LIBRARY JANSSON_INCLUDE_DIR)

IF(JANSSON_FOUND)
  SET(JANSSON_LIBRARIES ${JANSSON_LIBRARY})
  SET(JANSSON_INCLUDE_DIRS ${JANSSON_INCLUDE_DIR})
ENDIF(JANSSON_FOUND)

MARK_AS_ADVANCED(
  JANSSON_INCLUDE_DIR
  JANSSON_LIBRARY
)